GSV_CITIES_PATH = "D:\\Github\\gsv-cities\\datasets\\gsv_xs\\train\\"
DF_PATH = "D:\\Github\\gsv-cities\\datasets\\gsv_xs\dataframes\\"
GT_ROOT = "D:\\Github\\gsv-cities\\datasets\\"
SF_XS_PATH = "D:\\Github\\gsv-cities\\datasets\\SF_XS\\"
TOKYO_XS_PATH = "D:\\Github\\gsv-cities\\datasets\\Tokyo_XS\\"
