GSV_CITIES_PATH = "datasets/gsv_xs/train/"
DF_PATH = "datasets/gsv_xs/dataframes/"
GT_ROOT = "datasets/"
SF_XS_PATH = "datasets/sf_xs_dataset/"
TOKYO_XS_PATH = "datasets/tokyo_xs/"
MPS_PATH = "datasets/msls_val/"
