GSV_CITIES_PATH = "D:\\Github\\gsv-cities\\datasets\\gsv_xs\\train"
DF_PATH = "D:\\Github\\gsv-cities\\datasets\\gsv_xs\\dataframes"
GT_ROOT = "/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/"
SF_XS_PATH = "/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/sf_xs_dataset/"
TOKYO_XS_PATH = "/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/tokyo_xs_dataset/"
ROBOTCAR_PATH = "/Users/hadiibrahim/Dev/POLITO/gsv-cities/datasets/robotcar_dataset"
